# Generated by Django 4.2 on 2024-03-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companie_address_companie_city_and_more'),
        ('users', '0002_alter_user_pictureurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTankMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsmtto', models.JSONField()),
                ('questionviews', models.JSONField()),
                ('questionsdeterioration', models.JSONField()),
                ('tankidentification', models.JSONField()),
                ('observationsandresults', models.JSONField()),
                ('signatures', models.JSONField()),
                ('photos', models.JSONField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Espera'), (2, 'Rechazado'), (3, 'Aprobado')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporttankmovil', to='companies.companie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporttankmovil', to='users.user')),
                ('userCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporttankmovil', to='companies.usercompany')),
            ],
        ),
    ]
