# Generated by Django 4.2 on 2024-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporttankmovil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttankmovil',
            name='idcerticate',
            field=models.CharField(default='', max_length=30),
        ),
    ]
