# Generated by Django 4.2 on 2024-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_idcerticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='idcerticate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
